import { useState } from "react";
import { useNavigate } from "react-router-dom";

const API = import.meta.env.VITE_API_URL;
// =====================================================
// HELPERS
// =====================================================

// getRoleName handles both string and dict role (backend returns dict)
function getRoleName(role) {
  if (!role) return "Software Engineer";
  if (typeof role === "object") return role.role ?? "Software Engineer";
  return role;
}

// Questions are generated by the backend /generate-questions endpoint (llm_module.py)

// =====================================================
// OPTION BUTTON
// =====================================================

function OptionBtn({ label, state, onClick }) {
  // state: "idle" | "correct" | "wrong" | "reveal"
  const colors = {
    idle:    { bg: "#fff",      border: "#e5e7eb", text: "#1f2937", icon: null },
    correct: { bg: "#dcfce7",   border: "#16a34a", text: "#15803d", icon: "✓" },
    wrong:   { bg: "#fee2e2",   border: "#dc2626", text: "#b91c1c", icon: "✗" },
    reveal:  { bg: "#fef9c3",   border: "#ca8a04", text: "#92400e", icon: "★" },
  };
  const c = colors[state];

  return (
    <button
      onClick={onClick}
      disabled={state !== "idle"}
      style={{
        width: "100%",
        textAlign: "left",
        background: c.bg,
        border: `2px solid ${c.border}`,
        borderRadius: 12,
        padding: "13px 18px",
        fontSize: 14,
        fontWeight: state === "idle" ? 500 : 700,
        color: c.text,
        cursor: state === "idle" ? "pointer" : "default",
        display: "flex",
        alignItems: "center",
        gap: 10,
        transition: "all 0.18s",
        fontFamily: "inherit",
        boxShadow: state === "idle" ? "0 1px 3px rgba(0,0,0,0.05)" : "none",
      }}
      onMouseEnter={(e) => {
        if (state === "idle") e.currentTarget.style.borderColor = "#6366f1";
      }}
      onMouseLeave={(e) => {
        if (state === "idle") e.currentTarget.style.borderColor = "#e5e7eb";
      }}
    >
      {c.icon && (
        <span style={{
          width: 22, height: 22, borderRadius: "50%",
          background: c.border, color: "#fff",
          display: "flex", alignItems: "center", justifyContent: "center",
          fontSize: 12, fontWeight: 900, flexShrink: 0,
        }}>
          {c.icon}
        </span>
      )}
      {label}
    </button>
  );
}

// =====================================================
// SINGLE QUESTION CARD
// =====================================================

function QuestionCard({ q, index, total }) {
  const [chosen, setChosen] = useState(null); // null = unanswered

  const handlePick = (i) => {
    if (chosen !== null) return; // already answered
    setChosen(i);
  };

  const getState = (i) => {
    if (chosen === null) return "idle";
    if (i === q.correct) return chosen === i ? "correct" : "reveal";
    if (i === chosen)    return "wrong";
    return "idle";
  };

  const answered  = chosen !== null;
  const gotRight  = chosen === q.correct;

  return (
    <div style={{
      background: "#fff",
      border: "1px solid #e5e7eb",
      borderRadius: 20,
      padding: "28px 28px 24px",
      boxShadow: "0 2px 16px rgba(0,0,0,0.05)",
    }}>
      {/* Question header */}
      <div style={{ display: "flex", gap: 14, alignItems: "flex-start", marginBottom: 20 }}>
        <div style={{
          minWidth: 36, height: 36, borderRadius: "50%",
          background: answered
            ? (gotRight ? "#16a34a" : "#dc2626")
            : "linear-gradient(135deg,#6366f1,#4f46e5)",
          color: "#fff",
          display: "flex", alignItems: "center", justifyContent: "center",
          fontSize: 13, fontWeight: 800, flexShrink: 0,
          transition: "background 0.3s",
        }}>
          {answered ? (gotRight ? "✓" : "✗") : index + 1}
        </div>
        <div>
          <p style={{ fontSize: 11, fontWeight: 700, color: "#9ca3af", letterSpacing: "0.08em", textTransform: "uppercase", margin: "0 0 6px" }}>
            Question {index + 1} of {total}
          </p>
          <p style={{ fontSize: 15, fontWeight: 600, color: "#111827", lineHeight: 1.65, margin: 0 }}>
            {q.question}
          </p>
        </div>
      </div>

      {/* Options */}
      <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
        {q.options.map((opt, i) => (
          <OptionBtn key={i} label={opt} state={getState(i)} onClick={() => handlePick(i)} />
        ))}
      </div>

      {/* Feedback pill */}
      {answered && (
        <div style={{
          marginTop: 16,
          padding: "10px 16px",
          borderRadius: 10,
          background: gotRight ? "#f0fdf4" : "#fef2f2",
          border: `1px solid ${gotRight ? "#bbf7d0" : "#fecaca"}`,
          fontSize: 13,
          fontWeight: 600,
          color: gotRight ? "#15803d" : "#991b1b",
          display: "flex",
          alignItems: "center",
          gap: 8,
        }}>
          {gotRight
            ? "🎉 Correct! Well done."
            : `💡 Correct answer: ${q.options[q.correct]}`}
        </div>
      )}
    </div>
  );
}

// =====================================================
// SCORE SUMMARY
// =====================================================

function ScoreBadge({ questions }) {
  // Count how many have been answered correctly
  // (We can't introspect child state, so this is passed as a prop)
  return null; // Handled inline in parent
}

// =====================================================
// MAIN COMPONENT
// =====================================================

export default function Practice() {
  const [questions, setQuestions] = useState([]);
  const [answers,   setAnswers]   = useState({}); // index → chosen option index
  const [loading,   setLoading]   = useState(false);
  const [error,     setError]     = useState("");

  const navigate = useNavigate();

  // ── Generate questions ──────────────────────────────────────────
  const generateQuestions = async () => {
    setError("");
    setQuestions([]);
    setAnswers({});

    const raw = localStorage.getItem("resumeData");
    if (!raw) {
      setError("Please upload and analyze your resume first.");
      return;
    }

    let resumeData;
    try {
      resumeData = JSON.parse(raw);
    } catch {
      setError("Resume data is corrupted. Please re-upload your resume.");
      return;
    }

    if (!resumeData.role) {
      setError("Role not found. Please re-analyze your resume.");
      return;
    }

    setLoading(true);
    try {
      // Call the backend — it now returns {"questions": [...MCQ objects...]}
      const role          = getRoleName(resumeData.role);
      const matchedSkills = resumeData.matched_skills ?? [];
      const missingSkills = resumeData.missing_skills ?? [];

      const response = await fetch(`${API}/generate-practice`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ role, matched_skills: matchedSkills, missing_skills: missingSkills }),
      });

      if (!response.ok) throw new Error(`Server error ${response.status}`);

      const data = await response.json();
      if (data.error) throw new Error(data.error);

      // questions is already a parsed array from the backend
      let mcqs = data.questions;

      // Safety: if the backend somehow returned a string, parse it
      if (typeof mcqs === "string") {
        try { mcqs = JSON.parse(mcqs); } catch { throw new Error("Could not parse questions from server."); }
      }

      if (!Array.isArray(mcqs) || mcqs.length === 0) throw new Error("No questions returned.");
      setQuestions(mcqs);
    } catch (e) {
      setError(e.message || "Failed to generate questions.");
    }
    setLoading(false);
  };

  // Track answers for score display
  const handleAnswer = (qIndex, chosenIndex, correct) => {
    setAnswers((prev) => ({ ...prev, [qIndex]: { chosen: chosenIndex, correct } }));
  };

  const answeredCount = Object.keys(answers).length;
  const correctCount  = Object.values(answers).filter((a) => a.chosen === a.correct).length;

  // ── Render ──────────────────────────────────────────────────────
  return (
    <div style={{
      minHeight: "100vh",
      background: "#f8fafc",
      fontFamily: "'DM Sans', system-ui, sans-serif",
      paddingBottom: 80,
    }}>
      {/* Header */}
      <div style={{
        background: "linear-gradient(135deg,#6366f1,#06b6d4)",
        padding: "60px 24px 48px",
        textAlign: "center",
        color: "#fff",
      }}>
        <h1 style={{ fontSize: 48, fontWeight: 800, marginBottom: 12, margin: "0 0 12px" }}>
          Practice Questions
        </h1>
        <p style={{ fontSize: 17, opacity: 0.85, maxWidth: 560, margin: "0 auto" }}>
          AI-generated MCQs tailored to your resume and skill gaps. Click an option to reveal the answer.
        </p>
      </div>

      {/* Content */}
      <div style={{ maxWidth: 780, margin: "0 auto", padding: "40px 24px" }}>

        {/* Error */}
        {error && (
          <div style={{
            background: "#fef2f2", border: "1px solid #fca5a5", borderRadius: 12,
            padding: "14px 20px", color: "#dc2626", fontSize: 14, fontWeight: 600,
            textAlign: "center", marginBottom: 24,
          }}>
            ⚠️ {error}
          </div>
        )}

        {/* Score bar — only show when at least 1 answered */}
        {questions.length > 0 && answeredCount > 0 && (
          <div style={{
            background: "#fff", border: "1px solid #e5e7eb", borderRadius: 16,
            padding: "16px 24px", marginBottom: 28,
            display: "flex", alignItems: "center", justifyContent: "space-between",
            boxShadow: "0 2px 12px rgba(0,0,0,0.04)",
          }}>
            <span style={{ fontSize: 14, fontWeight: 700, color: "#374151" }}>
              Progress: {answeredCount} / {questions.length} answered
            </span>
            <span style={{
              fontSize: 15, fontWeight: 800,
              color: correctCount / answeredCount >= 0.7 ? "#16a34a" : "#dc2626",
            }}>
              {correctCount} / {answeredCount} correct
            </span>
          </div>
        )}

        {/* Generate button */}
        <div style={{ display: "flex", justifyContent: "center", marginBottom: 36, gap: 12, flexWrap: "wrap" }}>
          <button
            onClick={generateQuestions}
            disabled={loading}
            style={{
              background: loading ? "#e5e7eb" : "linear-gradient(135deg,#6366f1,#4f46e5)",
              color: loading ? "#9ca3af" : "#fff",
              border: "none", padding: "14px 32px", borderRadius: 14,
              fontSize: 15, fontWeight: 700,
              cursor: loading ? "not-allowed" : "pointer",
              boxShadow: loading ? "none" : "0 4px 20px rgba(99,102,241,0.35)",
              fontFamily: "inherit",
            }}
          >
            {loading ? "⏳ Generating…" : questions.length ? "🔄 Regenerate" : "✨ Generate Practice Questions"}
          </button>

          {questions.length > 0 && (
            <button
              onClick={() => navigate("/mock")}
              style={{
                background: "linear-gradient(135deg,#f97316,#ea580c)",
                color: "#fff", border: "none", padding: "14px 32px", borderRadius: 14,
                fontSize: 15, fontWeight: 700, cursor: "pointer",
                boxShadow: "0 4px 20px rgba(249,115,22,0.35)", fontFamily: "inherit",
              }}
            >
              🎯 Start Mock Interview
            </button>
          )}
        </div>

        {/* Loading skeleton */}
        {loading && (
          <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
            {[1, 2, 3, 4].map((i) => (
              <div key={i} style={{
                height: 180, borderRadius: 20,
                background: "linear-gradient(90deg,#e5e7eb 25%,#f3f4f6 50%,#e5e7eb 75%)",
                backgroundSize: "200% 100%",
                animation: "shimmer 1.4s infinite",
              }} />
            ))}
          </div>
        )}

        {/* Questions */}
        {!loading && questions.length > 0 && (
          <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
            {questions.map((q, i) => (
              <AnswerableCard
                key={i}
                q={q}
                index={i}
                total={questions.length}
                onAnswer={(chosen) => handleAnswer(i, chosen, q.correct)}
              />
            ))}
          </div>
        )}
      </div>

      <style>{`
        @keyframes shimmer {
          0%   { background-position: 200% 0; }
          100% { background-position: -200% 0; }
        }
      `}</style>
    </div>
  );
}

// Wrapper so parent can track answers via callback
function AnswerableCard({ q, index, total, onAnswer }) {
  const [chosen, setChosen] = useState(null);

  const handlePick = (i) => {
    if (chosen !== null) return;
    setChosen(i);
    onAnswer(i);
  };

  const getState = (i) => {
    if (chosen === null) return "idle";
    if (i === q.correct) return chosen === i ? "correct" : "reveal";
    if (i === chosen)    return "wrong";
    return "idle";
  };

  const answered = chosen !== null;
  const gotRight = chosen === q.correct;

  return (
    <div style={{
      background: "#fff",
      border: `1px solid ${answered ? (gotRight ? "#bbf7d0" : "#fecaca") : "#e5e7eb"}`,
      borderRadius: 20,
      padding: "28px 28px 24px",
      boxShadow: "0 2px 16px rgba(0,0,0,0.05)",
      transition: "border-color 0.3s",
    }}>
      {/* Question header */}
      <div style={{ display: "flex", gap: 14, alignItems: "flex-start", marginBottom: 20 }}>
        <div style={{
          minWidth: 36, height: 36, borderRadius: "50%",
          background: answered
            ? (gotRight ? "#16a34a" : "#dc2626")
            : "linear-gradient(135deg,#6366f1,#4f46e5)",
          color: "#fff",
          display: "flex", alignItems: "center", justifyContent: "center",
          fontSize: 13, fontWeight: 800, flexShrink: 0,
          transition: "background 0.3s",
        }}>
          {answered ? (gotRight ? "✓" : "✗") : index + 1}
        </div>
        <div style={{ flex: 1 }}>
          <p style={{
            fontSize: 11, fontWeight: 700, color: "#9ca3af",
            letterSpacing: "0.08em", textTransform: "uppercase", margin: "0 0 6px",
          }}>
            Question {index + 1} of {total}
          </p>
          <p style={{ fontSize: 15, fontWeight: 600, color: "#111827", lineHeight: 1.65, margin: 0 }}>
            {q.question}
          </p>
        </div>
      </div>

      {/* Options — vertical */}
      <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
        {q.options.map((opt, i) => {
          const state = getState(i);
          const colors = {
            idle:    { bg: "#fff",    border: "#e5e7eb", text: "#1f2937" },
            correct: { bg: "#dcfce7", border: "#16a34a", text: "#15803d" },
            wrong:   { bg: "#fee2e2", border: "#dc2626", text: "#b91c1c" },
            reveal:  { bg: "#fef9c3", border: "#ca8a04", text: "#92400e" },
          };
          const c = colors[state];
          return (
            <button
              key={i}
              onClick={() => handlePick(i)}
              disabled={chosen !== null}
              style={{
                width: "100%", textAlign: "left",
                background: c.bg, border: `2px solid ${c.border}`,
                borderRadius: 12, padding: "13px 18px",
                fontSize: 14, fontWeight: state === "idle" ? 500 : 700,
                color: c.text,
                cursor: chosen === null ? "pointer" : "default",
                display: "flex", alignItems: "center", gap: 10,
                transition: "all 0.18s", fontFamily: "inherit",
                boxShadow: state === "idle" ? "0 1px 3px rgba(0,0,0,0.05)" : "none",
              }}
              onMouseEnter={(e) => { if (chosen === null) e.currentTarget.style.borderColor = "#6366f1"; }}
              onMouseLeave={(e) => { if (chosen === null) e.currentTarget.style.borderColor = "#e5e7eb"; }}
            >
              {state !== "idle" && (
                <span style={{
                  width: 20, height: 20, borderRadius: "50%",
                  background: c.border, color: "#fff", flexShrink: 0,
                  display: "flex", alignItems: "center", justifyContent: "center",
                  fontSize: 11, fontWeight: 900,
                }}>
                  {state === "correct" ? "✓" : state === "wrong" ? "✗" : "★"}
                </span>
              )}
              {opt}
            </button>
          );
        })}
      </div>

      {/* Feedback */}
      {answered && (
        <div style={{
          marginTop: 16, padding: "10px 16px", borderRadius: 10,
          background: gotRight ? "#f0fdf4" : "#fef2f2",
          border: `1px solid ${gotRight ? "#bbf7d0" : "#fecaca"}`,
          fontSize: 13, fontWeight: 600,
          color: gotRight ? "#15803d" : "#991b1b",
          display: "flex", alignItems: "center", gap: 8,
        }}>
          {gotRight
            ? "🎉 Correct! Well done."
            : `💡 Correct answer: ${q.options[q.correct]}`}
        </div>
      )}
    </div>
  );
}